### ISSUE TITLE
🎨 Context Templates for Common Stacks

### ISSUE THREAD

**Issue by MacroMan5** [MacroMan5/claude-orchestrator-framework#28]
## Overview
Create pre-built context templates for common frameworks (Django, React, FastAPI, etc.) to enable instant context preparation.

## Goal
Auto-detect project type and apply appropriate context template for faster setup.

## Success Criteria
- [ ] Templates for 5+ common stacks
- [ ] Auto-detection of project type
- [ ] Template customization based on project structure
- [ ] Fast template application (< 5 seconds)
- [ ] Template validation and testing

### Sub-tasks:
- [ ] **Project Type Detection** (2h)
  - Analyze package.json, requirements.txt, etc.
  - Detect framework from imports and dependencies
  - Handle polyglot projects

- [ ] **Template Creation** (2h)
  - Django template with models, views, urls
  - React template with components, hooks, routing
  - FastAPI template with routes, models, dependencies
  - Node.js template with modules, middleware

### Supported Stacks:
- **Django**: Models, views, URLs, templates, settings
- **React**: Components, hooks, routing, state management
- **FastAPI**: Routes, models, dependencies, middleware
- **Node.js**: Modules, Express routes, middleware
- **Flask**: Routes, models, templates, blueprints

### Template Structure:
```yaml
name: django_web_app
detection:
  files: ['manage.py', 'django']
  requirements: ['Django>=']
context_patterns:
  - 'models/*.py'
  - 'views/*.py'
  - 'urls.py'
  - 'settings/*.py'
  - 'templates/**/*.html'
```

## Files to Modify/Create
- `templates/stacks/` (new directory)
- `core/stack_detector.py` (new)
- `core/template_engine.py` (new)

## Priority: Medium
Improves developer experience for common project types.

## Labels: enhancement, medium-priority, templates
